### ISSUE TITLE
Anticipate ggplotly use and don't style text

### ISSUE THREAD

**Issue by jonocarroll** [s6juncheng/ggpval#8]
Thanks for this package! I use {plotly} often using `ggplotly(p)` and was disappointed when {ggsignif} was unable to convert. Thankfully, {ggpval} has no such issue, however the styling of the text (italic 'P') does not carry over.

![ggpval](https://user-images.githubusercontent.com/9496865/90192518-40ff5e80-de02-11ea-84c5-62de5481597f.jpg)

I appreciate that this isn't any fault of {ggpval} but in anticipation of this use case, how about an optional argument to disable styling of the text, so that it goes through `ggplotly()` verbatim?
<details>
<summary>example code:</summary>

```r
# R.version.string
# [1] "R version 3.6.1 (2019-07-05)"
# packageVersion("ggpval")
# [1] ‘0.2.3’

library(ggplot2)
plt <- ggplot(mtcars, aes(factor(gear), mpg)) +
  geom_boxplot() + 
  geom_jitter()
p <- ggpval::add_pval(plt, pairs = list(c(1, 2)), test = "t.test")
plotly::ggplotly(p) 
```

</details>

**Comment by s6juncheng** [comment]
Hi @jonocarroll thanks for using the package, sorry for the delayed reply. 

Since `ggplotly` is wrapping the text differently, I added an option specifically for that. I updated the repo. One can install the updated dev version with ```devtools::install_github("s6juncheng/ggpval")```. The CRAN package will be updated in the next few days. After the installation, you can simply give the `plotly=TRUE` option, the text style will also be rendered:

```
library(ggplot2)
plt <- ggplot(mtcars, aes(factor(gear), mpg)) +
  geom_boxplot() + 
  geom_jitter()
p <- ggpval::add_pval(plt, pairs = list(c(1, 2)), test = "t.test", plotly=TRUE)
plotly::ggplotly(p) 
```

**Comment by jonocarroll** [comment]
Nice! Confirmed as working. Many thanks!!!
